name: Deploy To GitHub Pages And Server

env:
  ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
  SERVER_DOMAIN: uestcmsc-webapp.lyh543.cn
  SERVER_USERNAME: root

on:
  push:
    branches: [ master, lyh543 ]

jobs:
  # test:
  #   runs-on: ubuntu-latest

  #   services:
  #     mysql:
  #       image: mysql:8
  #       env:
  #         MYSQL_ROOT_PASSWORD: testtest
  #         MYSQL_DATABASE: uestcmsc_webapp
  #       ports:
  #         - 3306:3306

  #   strategy:
  #     max-parallel: 3
  #     matrix:
  #       python-version: [3.7, 3.8, 3.9]

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Python ${{ matrix.python-version }}
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #     - name: Install Dependencies
  #       run: |
  #         cp config.template.py config.py
  #         python3 -m pip install --upgrade pip
  #         pip3 install -r requirements.txt
  #     - name: Run Tests
  #       run: |
  #         python3 manage.py makemigrations accounts activities cloud comment gallery users --noinput
  #         python3 manage.py migrate --noinput
  #         coverage run --source=./ manage.py test --noinput
  #     - name: Coverage Report
  #       run: |
  #         coverage report -m
  # 
  deploy:
    # needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2

      - name: Install and Build ðŸ”§
        run: |
          npm install
          npm run build
          cp dist/index.html dist/200.html # GitHub Pages ä¸Šä¸å­˜åœ¨çš„ uri ä¼šè¢«é‡å®šå‘åˆ° 200.html

      - name: Setup SSH Environment
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa # é…ç½®ç§˜é’¥
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan $SERVER_DOMAIN >> ~/.ssh/known_hosts

      - name: Deploy ðŸš€ To GitHub
        uses: JamesIves/github-pages-deploy-action@132898c54c57c7cc6b80eb3a89968de8fc283505
        with:
          SSH: true
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch

      - name: Run SSH Command - Git Pull
        run: |
          ssh ${SERVER_USERNAME}@${SERVER_DOMAIN} < .github/workflows/vue-deploy.sh
